# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'teatime-lists' do
  use_frameworks!

  # Auth
  pod 'Parse'
  pod 'Parse/FacebookUtils'
  pod 'Parse/UI'
  pod 'FBSDKCoreKit', '~> 4.28.0'
  pod 'FBSDKLoginKit'
  
  # RFP
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  
  # Utilities
  pod 'Alamofire'
  pod 'TinyConstraints'
  pod 'SwiftyJSON'
  

  # Maps
  pod 'GoogleMaps'
  pod 'GooglePlaces'

  # Pods for teatime-lists

  target 'teatime-listsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
