# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'teatime-lists' do
  use_frameworks!

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'FBSDKCoreKit'  
  pod 'FBSDKLoginKit'
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  pod 'Moya', '~> 11.0'
  pod 'Moya/RxSwift', '~> 11.0'
  pod 'Kingfisher', '~> 4.0'
  pod 'TinyConstraints'

  # Pods for teatime-lists

  target 'teatime-listsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
